version: '3'
services:
    # PHP Service
    app:
        build:
            context: ./docker-compose/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - '2201:22'
        networks:
            - laravel
    # Database Service
    db:
        image: mysql:5.7
        container_name: homeowner-app-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homeowner
            MYSQL_ROOT_PASSWORD: password
        networks:
            - laravel
    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: homeowner-app-nginx
        ports:
            - '80:80'
        volumes:
            - .:/var/www/html
            - ./docker-compose/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - db
        networks:
            laravel:
                aliases:
                    - homeowner.local
networks:
    laravel:
